Repository kuberhealthy/kuberhealthy, pull requests merged in 2019-10, with the labels that each got.

#211 gitignore file and square logo
  .gitignore
  images/logo-square.png
Labels: documentation

#209 Implement gosec #172
  Dockerfile
Labels: tooling

#226 add deployment check
  Makefile
  README.md
  cmd/deployment-check/Dockerfile
  cmd/deployment-check/deployment-check.yaml
  cmd/deployment-check/deployment.go
  cmd/deployment-check/deployment_test.go
  cmd/deployment-check/input.go
  cmd/deployment-check/main.go
  cmd/deployment-check/run_check.go
  cmd/deployment-check/service.go
  cmd/deployment-check/service_requester.go
  cmd/deployment-check/service_test.go
Labels: feature request, proposal
